3.Django/firstprj/firstprj/apps/notes/urls.py
from django.urls import path

from . import views
# from . views import MyRegisterFormView


app_name = 'notes'
urlpatterns = [
	path('', views.index, name = 'index'),
	path('create/', views.create_note, name = 'create'),
	path('<int:note_id>/', views.detail, name = 'detail'),
	path('<int:note_id>/delete/', views.delete_note, name = 'delete'),
	path('<int:note_id>/change/', views.change_note, name = 'change'),
	path('back/', views.back, name = 'back'),
	path('check/', views.check, name = 'check'),
]  

3.Django/firstprj/firstprj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('notes/', include('notes.urls')),
	path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

3.Django/firstprj/firstprj/apps/notes/models.py
from django.db import models

STATUS_CHOICES = ( 
    ("0", "Не выполнено"), 
    ("1", "В процессе"), 
    ("2", "Выполнено"), 
) 

class Note(models.Model):
	category_note = models.CharField('Категория', max_length = 100)
	text_note = models.TextField('Текст')
	pub_date = models.DateTimeField('Дата публикации')
	status_note = models.CharField(
		'Статус', 
		max_length = 20,
		choices = STATUS_CHOICES,
		default = '1')

	def __str__(self):
		return  f'Категория: {self.category_note},Текст заметки: {self.text_note[:15]}, Статус: {self.status_note}'

	class Meta:
		verbose_name = 'Заметку'
		verbose_name_plural = 'Заметки'

3.Django/firstprj/firstprj/apps/notes/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect

from django.urls import reverse

from .models import Note
from django.utils import timezone
import datetime

from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import FormView


def index(request):
	notes_list = Note.objects.order_by('-pub_date')
	return render(request, 'notes/list.html',{'notes_list':notes_list})

def detail(request,note_id):
	try:
		a = Note.objects.get(id = note_id)
	except:
		raise Http404("Такой заметки нет")

	return render(request, 'notes/detail.html',{'note': a})

def create_note(request):
	Note.objects.create(category_note = request.POST['category'],text_note = request.POST['text'],pub_date = timezone.now())
	return redirect(request.META.get('HTTP_REFERER'))

def delete_note(request,note_id):
	del_= Note.objects.get(id = note_id)
	del_.delete()	
	return redirect('notes:index')

def change_note(request,note_id):
	ch = Note.objects.get(id = note_id)
	ch.category_note = request.POST['category']
	ch.text_note = request.POST['text']
	ch.status_note = request.POST['status']
	ch.pub_date = timezone.now()
	ch.save()
	return redirect(request.META.get('HTTP_REFERER'))
	# return render(request, 'notes/detail.html',{'note': ch})

def back(request):
	return redirect('notes:index')


def check(request):
	return redirect(request.META.get('HTTP_REFERER'))

3.Django/firstprj/firstprj/templates/base.html
<!DOCTYPE html>
<html lang='ru'>
<head>
	<meta charset="utf-8">
	<title>{% block title %}My site{% endblock%}</title>
</head>
<body>

{% block content %}{% endblock %}

</body>
</html>

3.Django/firstprj/firstprj/templates/notes/detail.html
{% extends 'base.html' %}

{% block title %}{{note.category_note}}{% endblock %}

{% block content %}

<h2>{{note.category_note}}</h2>

<p>{{note.text_note}}</p>

<em>{{note.pub_date}}</em>

<hr>
<hr>

<form action="{% url 'notes:delete' note.id %}" method="POST">
	{% csrf_token %}
	<button type="submit">Удалить заметку</button>
</form>

<hr>
<hr>

<form action="{% url 'notes:change' note.id %}" method="POST">
	{% csrf_token %}
	<input type="text" value="{{note.category_note}}" required="" placeholder="Введите название" name="category"><br>
	
	<textarea name="text" required="" placeholder="Введите текст" cols="40" rows="10">{{note.text_note}}
	</textarea><br>
	
	<select name="status">
		<option {% if note.status_note == '0' %}selected{% endif %} value="0">Не выполнено</option>
		<option {% if note.status_note == '1' %}selected{% endif %} value="1">В процессе</option>
		<option {% if note.status_note == '2' %}selected{% endif %} value="2">Выполнено</option>
	</select>

	<button type="submit">Изменить заметку</button>
</form>

<form action="{% url 'notes:back' %}" method="POST">
	{% csrf_token %}
	<button type="submit">Назад</button>
</form>

{% endblock %}

3.Django/firstprj/firstprj/templates/notes/list.html
{% extends 'base.html' %}

{% block title %}Заметки{% endblock %}

{% block content %}
	{% if notes_list %}
	
		{% for a in notes_list %}

			<a href="{% url 'notes:detail' a.id %}">{{a.category_note}}</a>

		{% endfor %}

	{% else %}
		Заметок нет...
	{% endif %}
<hr>

<hr>

<form action="{% url 'notes:create' %}" method="POST">

{% csrf_token %}

<input type="text" required="" placeholder="Введите название" name="category"><br>
<textarea name="text" required="" placeholder="Текст заметки" cols="40" rows="10"></textarea><br>
<button type="submit">Добавить заметку</button></form>
{% endblock %}